/**
 * This function is the extracted "brain" of our Machine Learning model.
 * It takes the user's quiz scores and applies the exact Decision Tree rules
 * generated by our Python training script to determine if they need ADHD support.
 * 
 * @param {number} inattentiveScore - The user's score from the inattention questions
 * @param {number} hyperImpulsiveScore - The user's score from the hyperactivity questions
 * @returns {boolean} - True if the app should enable High-Support Mode
 */
export function evaluateAdhdSupport(inattentiveScore, hyperImpulsiveScore) {
  if (inattentiveScore <= 59.50) {
    if (inattentiveScore <= 38.00) {
      if (inattentiveScore <= 22.50) {
        return false; // class: 0.0 (Standard Mode)
      } else {
        return true;  // class: 3.0 (ADHD-Inattentive -> Support Mode)
      }
    } else {
      if (hyperImpulsiveScore <= 62.50) {
        return false; // class: 0.0 (Standard Mode)
      } else {
        return true;  // class: 1.0 (ADHD-Combined -> Support Mode)
      }
    }
  } 
  else {
    if (hyperImpulsiveScore <= 55.50) {
      if (inattentiveScore <= 63.00) {
        return false; // class: 0.0 (Standard Mode)
      } else {
        return true;  // class: 3.0 (ADHD-Inattentive -> Support Mode)
      }
    } else {
      // If hyperImpulsive is > 55.50, all paths lead to class 1.0
      return true;    // class: 1.0 (ADHD-Combined -> Support Mode)
    }
  }
}